### ISSUE TITLE
Broken link in Readme

### ISSUE THREAD

**Issue by dmolley** [nubisware/egdsimulator#6]
The first link <http://[geplc.com](http://geplc.com/downloads/Labs/GFS-384%20M09%20EGD.pdf)/downloads/Labs/GFS-384%20M09%20EGD.pdf> in the ReadMe file is broken.

**Comment by dcore94** [comment]
Yeah, sorry. Seems like GE has changed a lot since then.
We've been able to find the pdf in the wayback machine:

https://web.archive.org/web/20180219025736/http://geplc.com/downloads/Labs/GFS-384%20M09%20EGD.pdf

We have to check if including it directly in the code repository does infringe any policy. If not we'll merge it directly into a proper section of the code.

Thanks for reporting anyway!
